name: Call a reusable workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: mowies/reuse-workflow-test-called/.github/workflows/called-pipeline.yml@main
